# -*- coding: utf-8 -*-
"""Unified Language Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mElGW7ALsouXHfKTx1OhWL1hhNQQ1EAw
"""

!pip install transformers datasets accelerate evaluate

"""
Unified Language Model Demo
- Summarization (English)
- Translation (English → Italian)
- Sentiment Analysis
"""

# Install required libraries (for Colab, uncomment the line below)
# !pip install transformers datasets accelerate

from transformers import T5ForConditionalGeneration, T5Tokenizer
from transformers import MarianMTModel, MarianTokenizer, pipeline

def main():
    # Summarization Model (T5)
    t5_model_name = "t5-small"
    t5_tokenizer = T5Tokenizer.from_pretrained(t5_model_name)
    t5_model = T5ForConditionalGeneration.from_pretrained(t5_model_name)

    # Translation Model (English → Italian)
    mt_model_name = "Helsinki-NLP/opus-mt-en-it"
    mt_tokenizer = MarianTokenizer.from_pretrained(mt_model_name)
    mt_model = MarianMTModel.from_pretrained(mt_model_name)

    # Sentiment Analysis
    classifier = pipeline("sentiment-analysis")

    # User Input
    text = input("Enter an English text to summarize, translate, and analyze sentiment:\n")

    # Summarization
    input_text = "summarize: " + text
    inputs = t5_tokenizer(input_text, return_tensors="pt")
    output_ids = t5_model.generate(**inputs, max_length=100)
    summary = t5_tokenizer.decode(output_ids[0], skip_special_tokens=True)

    # Italian Translation
    mt_inputs = mt_tokenizer(summary, return_tensors="pt", padding=True)
    mt_output_ids = mt_model.generate(**mt_inputs)
    italian_translation = mt_tokenizer.decode(mt_output_ids[0], skip_special_tokens=True)

    # Sentiment Analysis
    sentiment_result = classifier(summary)[0]

    # Print Results
    print("\n--- Results ---")
    print("Original Text:\n", text)
    print("\nSummary:\n", summary)
    print("\nItalian Translation:\n", italian_translation)
    print("\nSentiment of Summary:\n", sentiment_result['label'], "Score:", sentiment_result['score'])


if __name__ == "__main__":
    main()

